# Generated by Django 4.2.13 on 2026-03-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='api_project_created_4ce842_idx',
            old_name='api_project_created_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='api_project_status_89cb34_idx',
            old_name='api_project_status_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='api_project_owner_i_235ae6_idx',
            old_name='api_project_owner_idx',
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
